import {expect,it} from 'vitest';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {NativeProgram,type NativeProgramArtifact} from '../../src/modelica-native-program';
import {fixture,I,inverse,multiply,mv,observationJacobian,pointCovariance,rotation,skew,transpose,zeros,type Fixture,type Matrix} from './rgbd-registration-uncertainty-fixtures';
const source=readFileSync('dev/artifacts/registration-uncertainty/initial-builtin-source.mo','utf8');
const artifact=JSON.parse(readFileSync('dev/artifacts/modelica-typed-slice-updates/original350-native.json','utf8')) as NativeProgramArtifact;
const output=process.env.RUMOCA_ORIGINAL350_REPORT_DIR!;
const sha=(s:string|Uint8Array)=>createHash('sha256').update(s).digest('hex');
const matrices=['relativeCovariance','observationCovariance','normalMatrix','noiseMatrix','observationJacobian'] as const;
function pivot(H:Matrix){if(H.some((r,i)=>!(r[i]>0&&r[i]<=1e100)))return 0;const scaled=H.map((row,i)=>row.map((v,j)=>v/Math.sqrt(H[i][i])/Math.sqrt(H[j][j])));let minimum=1;for(let k=0;k<6;k++){const d=scaled[k][k];minimum=Math.min(minimum,d);if(!(d>1e-10))break;for(let i=k+1;i<6;i++)for(let j=k+1;j<6;j++)scaled[i][j]-=scaled[i][k]*scaled[k][j]/d;}return minimum;}
const proper=(R:Matrix)=>R.flat().every(v=>Math.abs(v)<=1.000001)&&multiply(transpose(R),R).every((r,i)=>r.every((v,j)=>Math.abs(v-+(i===j))<=1e-6))&&Math.abs(R[0][0]*(R[1][1]*R[2][2]-R[1][2]*R[2][1])-R[0][1]*(R[1][0]*R[2][2]-R[1][2]*R[2][0])+R[0][2]*(R[1][0]*R[2][1]-R[1][1]*R[2][0])-1)<=1e-6;
function oracle(f:Fixture){
 const config=Number.isInteger(f.activeCount)&&f.activeCount>=0&&f.activeCount<=350&&f.baseline>0&&f.baseline<=1&&[f.referenceNoiseFx,f.currentNoiseFx,...f.referenceRgbFocal,...f.currentRgbFocal].every(v=>v>0&&v<=1e6);
 const pose=f.registrationAccepted===1&&[f.currentFromReference,f.referenceBodyRotation,f.opticalToBody].every(proper)&&[...f.translation,...f.cameraOriginBody].every(v=>Math.abs(v)<=100);
 let validCount=0,invalidCount=0;const H=zeros(6,6),M=zeros(6,6);
 for(let i=0;i<350;i++){const p=f.referencePoint[i],q=f.currentPoint[i];const selected=config&&i+1<=f.activeCount&&f.pairEnabled[i]===1&&[...p,...q].every(v=>Math.abs(v)<=100)&&p[2]>0&&q[2]>0;if(i+1<=f.activeCount&&f.pairEnabled[i]!==0&&!selected)invalidCount++;if(!selected)continue;validCount++;if(!pose)continue;
  const rotated=mv(f.currentFromReference,p),S=skew(rotated),J=I(3).map((r,k)=>[...r,...S[k].map(v=>-v)]),Cr=pointCovariance(p,f.referenceRgbFocal,f.referenceNoiseFx,f.baseline),Ct=pointCovariance(q,f.currentRgbFocal,f.currentNoiseFx,f.baseline),rot=multiply(multiply(f.currentFromReference,Cr),transpose(f.currentFromReference)),Sigma=Ct.map((r,a)=>r.map((v,b)=>v+rot[a][b])),h=multiply(transpose(J),J),m=multiply(multiply(transpose(J),Sigma),J);for(let a=0;a<6;a++)for(let b=0;b<6;b++){H[a][b]+=h[a][b];M[a][b]+=m[a][b];}}
 const minimumScaledPivot=pivot(H),hValid=minimumScaledPivot>1e-10;const G=pose?observationJacobian(f):zeros(6,6);if(!pose)for(let i=0;i<3;i++)G[i][i]=-1;
 let relative=zeros(6,6),observation=zeros(6,6);if(hValid){const inv=inverse(H);relative=multiply(multiply(inv,M),transpose(inv));observation=multiply(multiply(G,relative),transpose(G));}const cValid=pivot(observation)>1e-10;
 const rejectionReason=!config?1:!pose?2:invalidCount>0?3:validCount<3?4:!hValid?5:!cValid?6:0;if(rejectionReason){relative=zeros(6,6);observation=zeros(6,6);}return {relativeCovariance:relative,observationCovariance:observation,normalMatrix:H,noiseMatrix:M,observationJacobian:G,valid:+!rejectionReason,rejectionReason,validCount,invalidCount,minimumScaledPivot};
}
it('actual original8074 full350 native WASM matches independent 180-cell oracle and transport controls',async()=>{
 mkdirSync(output,{recursive:true});const report:Record<string,unknown>={status:'RUNNING',engine:'Node/V8 WebAssembly',sourceSha256:sha(source),moduleSha256:artifact.module_sha256,capacity:350,cases:[],fullSlam:false,throughputClaim:false,compilerBuild:false};const fixtures:unknown[]=[];let maxError=0;const save=()=>writeFileSync(output+'/report.json',JSON.stringify(report,null,2)+'\n');save();
 try{
 expect(sha(source)).toBe('8074f170f8316c4874f4517e1f4875924434fa1f58d27611a1ff93d719441ecd');expect(sha(new Uint8Array(artifact.module_bytes))).toBe('58de05687b5fa28c50d54b102d80c1b5cfb7ae131faf2a412fcad346057ccad5');
 let program=await NativeProgram.instantiate(artifact,source);expect(program.input('pairEnabled').length).toBe(350);expect(program.input('referencePoint').length).toBe(1050);
 const compare=(actual:number[],expected:number[],label:string)=>{expect(actual.length).toBe(expected.length);for(let i=0;i<actual.length;i++){const error=Math.abs(actual[i]-expected[i]);maxError=Math.max(maxError,error);expect(error,`${label}/${i}`).toBeLessThan(3e-8*Math.max(1,Math.abs(expected[i])));}};
 const run=(name:string,f:Fixture)=>{for(const [key,value] of Object.entries(f))program.input(key).set(Array.isArray(value)?value.flat():[value]);const p=new Uint8Array(program.memory.buffer,artifact.abi.p_offset,artifact.abi.p_count*8).slice();const expected=oracle(f);program.evaluate(0);expect(new Uint8Array(program.memory.buffer,artifact.abi.p_offset,p.length)).toEqual(p);for(const field of matrices)compare([...program.output(field)],expected[field].flat(),name+'/'+field);for(const field of ['valid','rejectionReason','validCount','invalidCount'] as const)expect(program.output(field)[0],name+'/'+field).toBe(expected[field]);compare([...program.output('minimumScaledPivot')],[expected.minimumScaledPivot],name+'/pivot');(report.cases as unknown[]).push({name,expectedValid:expected.valid,rejectionReason:expected.rejectionReason,validCount:expected.validCount,invalidCount:expected.invalidCount,cellsChecked:180});fixtures.push({name,pBytes:[...p],expected});save();return [...program.output('observationCovariance')];};
 run('general6DOF full350',fixture());const extrinsic=fixture();extrinsic.opticalToBody=rotation([1,-2,4],.81);extrinsic.cameraOriginBody=[.4,-.2,.3];extrinsic.referenceBodyRotation=rotation([-1,4,2],-.9);run('nonidentity extrinsics',extrinsic);
 const planar=fixture();planar.referencePoint.forEach(p=>p[2]=2);planar.currentPoint=planar.referencePoint.map(p=>mv(planar.currentFromReference,p).map((v,k)=>v+planar.translation[k]));run('planar rank2',planar);
 const sparse=fixture();sparse.pairEnabled.fill(0);for(const i of [0,100,220,349])sparse.pairEnabled[i]=1;for(let i=0;i<350;i++)if(!sparse.pairEnabled[i]){sparse.referencePoint[i].fill(NaN);sparse.currentPoint[i].fill(NaN);}run('sparse late maskedNaNs',sparse);
 for(const count of [0,2,-1,.5,351,NaN,Infinity]){const f=fixture();f.activeCount=count;run('invalid or insufficient count '+String(count),f);}for(const mask of [.5,NaN,2]){const f=fixture();f.pairEnabled[349]=mask;run('invalid late mask '+String(mask),f);}
 for(const field of ['baseline','referenceNoiseFx','currentNoiseFx'] as const){const f=fixture();f[field]=0;run('invalid '+field,f);}const nan=fixture();nan.currentPoint[349][2]=NaN;run('late active NaN',nan);
 const badPose=fixture();badPose.opticalToBody=[[-1,0,0],[0,1,0],[0,0,1]];run('improper pose',badPose);const declined=fixture();declined.registrationAccepted=0;run('registration declined',declined);const line=fixture();line.referencePoint=line.referencePoint.map((_,i)=>[0,0,2+i*.001]);line.currentPoint=line.referencePoint.map(p=>mv(line.currentFromReference,p).map((v,k)=>v+line.translation[k]));run('collinear degeneracy',line);
 const snapshot=run('recovery',fixture());program.reset();run('reset replay',fixture());compare([...program.output('observationCovariance')],snapshot,'reset');await expect(NativeProgram.instantiate(artifact,source+'\n// stale')).rejects.toThrow('does not match its source');program=await NativeProgram.instantiate(JSON.parse(JSON.stringify(artifact)),source);run('saved JSON reload',fixture());compare([...program.output('observationCovariance')],snapshot,'reload');
 const y=new Uint8Array(program.memory.buffer,0,artifact.abi.y_count*8).slice();const p=new Uint8Array(program.memory.buffer,artifact.abi.p_offset,artifact.abi.p_count*8).slice();const env:Record<string,WebAssembly.ImportValue>={memory:program.memory};for(const name of artifact.math_imports!)env[name]=(Math as unknown as Record<string,WebAssembly.ImportValue>)[name];const module=await WebAssembly.instantiate(new Uint8Array(artifact.module_bytes),{env});const execute=module.instance.exports.eval_assignments as (y:number,p:number,time:number,scratch:number,reserved:number)=>number;const scratchOffset=artifact.abi.scratch_offset;if(artifact.profile!=='native-direct-program-f64-v3'||typeof scratchOffset!=='number'||!Number.isSafeInteger(scratchOffset)||scratchOffset<0||scratchOffset%8!==0)throw new Error('Expected typed ABI scratch offset');const status=execute(1,artifact.abi.p_offset,0,scratchOffset,0);expect(status).toBe(1);expect(new Uint8Array(program.memory.buffer,0,y.length)).toEqual(y);expect(new Uint8Array(program.memory.buffer,artifact.abi.p_offset,p.length)).toEqual(p);run('ABI fault recovery',fixture());
 report.status='ACTUAL_ORIGINAL_FULL350_NATIVE_NUMERICS_PASS';report.maxAbsoluteError=maxError;report.matrixCellsChecked=fixtures.length*180;report.controls={immutableP:true,atomicABI:true,recovery:true,reset:true,savedJSONReload:true,staleSourceRefusal:true};writeFileSync(output+'/independent-browser-fixtures.json',JSON.stringify({sourcePath:'dev/artifacts/registration-uncertainty/initial-builtin-source.mo',sourceSha256:sha(source),artifactPath:'dev/artifacts/modelica-typed-slice-updates/original350-native.json',moduleSha256:artifact.module_sha256,capacity:350,cases:fixtures})+'\n');save();
 }catch(error){report.status='FAILED';report.failure=String(error);report.maxAbsoluteError=maxError;save();throw error;}
},120000);
