import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import init,* as rumoca from '@cognipilot/rumoca';

type Matrix=number[][];
type Quaternion=[number,number,number,number];
type State={q:Quaternion;p:number[];v:number[];ba:number[];bg:number[];P:Matrix;accepted:number;rejected:number;nis:number};
type Observation={dp:number[];theta:number[];C:Matrix;rotation?:Matrix};
const matrix=(n:number,m:number,f:(i:number,j:number)=>number):Matrix=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>f(i,j)));
const identity=(n:number)=>matrix(n,n,(i,j)=>+(i===j));
const zeros=(n:number,m:number)=>matrix(n,m,()=>0);
const transpose=(a:Matrix)=>matrix(a[0].length,a.length,(i,j)=>a[j][i]);
const multiply=(a:Matrix,b:Matrix)=>matrix(a.length,b[0].length,(i,j)=>a[i].reduce((s,x,k)=>s+x*b[k][j],0));
const add=(a:Matrix,b:Matrix)=>matrix(a.length,a[0].length,(i,j)=>a[i][j]+b[i][j]);
const norm=(v:number[])=>Math.hypot(...v);
function expQ(v:number[]):Quaternion {
  const a=norm(v),s=a===0?.5:Math.sin(a/2)/a;
  return [Math.cos(a/2),v[0]*s,v[1]*s,v[2]*s];
}
function productQ(a:Quaternion,b:Quaternion):Quaternion {
  const [w,x,y,z]=a,[W,X,Y,Z]=b;
  return [w*W-x*X-y*Y-z*Z,w*X+x*W+y*Z-z*Y,w*Y-x*Z+y*W+z*X,w*Z+x*Y-y*X+z*W];
}
const inverseQ=(q:Quaternion):Quaternion=>[q[0],-q[1],-q[2],-q[3]];
function canonicalQ(q:Quaternion):Quaternion {const scale=(q[0]<0?-1:1)/norm(q);return q.map(v=>v*scale) as Quaternion;}
function logQ(q:Quaternion):number[] {
  const p=canonicalQ(q),s=norm(p.slice(1)),scale=s===0?2:2*Math.atan2(s,p[0])/s;
  return p.slice(1).map(v=>v*scale);
}
function rotation(q:Quaternion):Matrix {
  const [w,x,y,z]=q;
  return [[1-2*(y*y+z*z),2*(x*y-w*z),2*(x*z+w*y)],
    [2*(x*y+w*z),1-2*(x*x+z*z),2*(y*z-w*x)],
    [2*(x*z-w*y),2*(y*z+w*x),1-2*(x*x+y*y)]];
}
// Independent Gaussian elimination with partial pivoting: the model uses Cholesky.
function solve(a:Matrix,b:Matrix):Matrix {
  const n=a.length,m=b[0].length,rows=a.map((r,i)=>[...r,...b[i]]);
  for(let k=0;k<n;k++){
    let p=k;for(let i=k+1;i<n;i++)if(Math.abs(rows[i][k])>Math.abs(rows[p][k]))p=i;
    [rows[k],rows[p]]=[rows[p],rows[k]];
    if(Math.abs(rows[k][k])<1e-30)throw new Error('singular oracle');
    for(let i=k+1;i<n;i++){
      const f=rows[i][k]/rows[k][k];for(let j=k;j<n+m;j++)rows[i][j]-=f*rows[k][j];
    }
  }
  const x=zeros(n,m);
  for(let i=n-1;i>=0;i--)for(let j=0;j<m;j++)x[i][j]=(rows[i][n+j]-rows[i].slice(i+1,n).reduce((s,v,k)=>s+v*x[i+1+k][j],0))/rows[i][i];
  return x;
}
// Positive LDL pivots independently validate the measurement covariance.
function positiveCovariance(c:Matrix):boolean {
  const n=c.length;
  for(let i=0;i<n;i++)for(let j=0;j<n;j++)if(Math.abs(c[i][j]-c[j][i])>1e-12+1e-8*Math.abs(c[j][i]))return false;
  const a=c.map(r=>[...r]);
  for(let k=0;k<n;k++){
    if(!(a[k][k]>0))return false;
    for(let i=k+1;i<n;i++)for(let j=k+1;j<n;j++)a[i][j]-=a[i][k]*a[j][k]/a[k][k];
  }
  return true;
}
// Differentiate Log(Exp(delta)^-1 Exp(delta+epsilon)); no Rodrigues/Jr copy.
function numericalReset(delta:number[]):Matrix {
  const q=expQ(delta),eps=1e-5;
  return transpose(Array.from({length:3},(_,axis)=>{
    const side=(sign:number)=>logQ(productQ(inverseQ(q),expQ(delta.map((v,i)=>v+(i===axis?sign*eps:0)))));
    const a=side(1),b=side(-1);return a.map((v,i)=>(v-b[i])/(2*eps));
  }));
}
function reference(s:State,o:Observation){
  const R=o.rotation??rotation(productQ(s.q,expQ(o.theta))),gram=multiply(transpose(R),R);
  const det=R[0][0]*(R[1][1]*R[2][2]-R[1][2]*R[2][1])-R[0][1]*(R[1][0]*R[2][2]-R[1][2]*R[2][0])+R[0][2]*(R[1][0]*R[2][1]-R[1][1]*R[2][0]);
  const validRotation=gram.every((r,i)=>r.every((v,j)=>Math.abs(v-+(i===j))<=1e-6))&&Math.abs(det-1)<=1e-6;
  const admissible=validRotation&&positiveCovariance(o.C);
  // The valid fixtures' observation is generated by independent quaternion composition.
  const innovation=[...o.dp,...logQ(expQ(o.theta))],indices=[0,1,2,6,7,8];
  const H=matrix(6,15,(i,j)=>+(indices[i]===j));
  const cross=matrix(15,6,(i,j)=>s.P[i][indices[j]]),S=matrix(6,6,(i,j)=>cross[indices[i]][j]+o.C[i][j]);
  const rhs=matrix(6,16,(i,j)=>j<15?cross[j][i]:innovation[i]);
  const solved=admissible?solve(S,rhs):zeros(6,16),K=transpose(solved.map(r=>r.slice(0,15)));
  const correction=K.map(r=>r.reduce((sum,v,j)=>sum+v*innovation[j],0));
  const nis=innovation.reduce((sum,v,i)=>sum+v*solved[i][15],0);
  const ba=s.ba.map((v,i)=>v+correction[i+9]),bg=s.bg.map((v,i)=>v+correction[i+12]);
  const accepted=admissible&&nis>=0&&nis<=22.46&&norm(innovation.slice(3))<=.35&&norm(ba)<=2&&norm(bg)<=.3;
  const KH=multiply(K,H),A=matrix(15,15,(i,j)=>+(i===j)-KH[i][j]);
  const joseph=add(multiply(multiply(A,s.P),transpose(A)),multiply(multiply(K,o.C),transpose(K)));
  const reset=identity(15),J=numericalReset(correction.slice(6,9));
  for(let i=0;i<3;i++)for(let j=0;j<3;j++)reset[i+6][j+6]=J[i][j];
  const posterior=multiply(multiply(reset,joseph),transpose(reset));
  const next:State={q:accepted?canonicalQ(productQ(s.q,expQ(correction.slice(6,9)))):s.q,
    p:accepted?s.p.map((v,i)=>v+correction[i]):s.p,v:accepted?s.v.map((v,i)=>v+correction[i+3]):s.v,
    ba:accepted?ba:s.ba,bg:accepted?bg:s.bg,P:accepted?matrix(15,15,(i,j)=>(posterior[i][j]+posterior[j][i])/2):s.P,
    accepted:s.accepted+ +accepted,rejected:s.rejected+ +!accepted,nis:admissible?nis:s.nis};
  return {admissible,accepted,innovation,H,cross,S,rhs,solved,K,correction,joseph,next};
}
const correlated=(n:number,diagonal:number[])=>{
  const L=matrix(n,n,(i,j)=>j>i?0:i===j?diagonal[i]:.013*Math.sin((i+1)*(j+2)*.37));
  return multiply(L,transpose(L));
};
const base=():State=>({q:expQ([.3,-.5,.7]),p:[1.2,-.4,2.3],v:[.5,-.1,.2],ba:[.1,-.07,.03],bg:[.01,-.02,.015],
  P:correlated(15,Array.from({length:15},(_,i)=>i<3?.1:i<6?.3:i<9?.15:i<12?.5:.05)),accepted:4,rejected:7,nis:17.25});
const observation=(theta=[.06,-.04,.03],dp=[.03,-.02,.01]):Observation=>({theta,dp,C:correlated(6,[.04,.04,.04,.025,.025,.025])});
type Input=[string,number];
const putMatrix=(inputs:Input[],name:string,a:Matrix)=>a.forEach((r,i)=>r.forEach((v,j)=>inputs.push([`${name}[${i+1},${j+1}]`,v])));
const putVector=(inputs:Input[],name:string,v:number[])=>v.forEach((x,i)=>inputs.push([`${name}[${i+1}]`,x]));
function poseInputs(s:State,o:Observation):Input[]{
  const inputs:Input[]=[['accepted_count',s.accepted],['rejected_count',s.rejected],['last_nis',s.nis],['solve_valid',0],['observation_covariance_valid',0]];
  putMatrix(inputs,'rotation',rotation(s.q));putMatrix(inputs,'observed_rotation',o.rotation??rotation(productQ(s.q,expQ(o.theta))));
  putMatrix(inputs,'covariance',s.P);putMatrix(inputs,'observation_covariance',o.C);putMatrix(inputs,'solved',zeros(6,16));
  for(const [name,v] of [['position',s.p],['velocity',s.v],['accel_bias',s.ba],['gyro_bias',s.bg],['observed_position',s.p.map((v,i)=>v+o.dp[i])]] as const)putVector(inputs,name,v);
  return inputs;
}

it('independent pose fixture oracle exercises dense cross-covariance and both trust gates',()=>{
  const accepted=reference(base(),observation());expect(accepted.accepted).toBe(true);
  expect(accepted.correction.every(v=>Math.abs(v)>1e-8)).toBe(true);
  expect(positiveCovariance(accepted.next.P)).toBe(true);
  expect(reference(base(),observation([.349,0,0],[0,0,0])).accepted).toBe(true);
  expect(reference(base(),observation([.351,0,0],[0,0,0])).accepted).toBe(false);
  const state={...base(),ba:[0,0,0],bg:[0,0,0],P:matrix(15,15,(i,j)=>i===j?.04:0)};
  for(const factor of [1-1e-7,1+1e-7])expect(reference(state,{theta:[0,0,0],dp:[Math.sqrt(22.46*.05)*factor,0,0],C:matrix(6,6,(i,j)=>i===j?.01:0)}).accepted).toBe(factor<1);
});

it('Modelica pose correction solves all16 RHS and preserves the full15-state Joseph/injection/reset and rejection semantics',async()=>{
  const directory=process.env.RUMOCA_BRANCH_PKG;
  const compiler:typeof rumoca=directory?await import(/* @vite-ignore */ pathToFileURL(resolve(directory,'rumoca_bind_wasm.js')).href):rumoca;
  await (directory?compiler.default:init)({module_or_path:readFileSync(directory?resolve(directory,'rumoca_bind_wasm_bg.wasm'):'public/vendor/rumoca/rumoca_bind_wasm_bg.wasm')});
  const source=['models/SPD6Solve.mo','models/ES15PoseCorrection.mo'].map(p=>readFileSync(p,'utf8')).join('\n');
  const initial=poseInputs(base(),observation());
  const trace=(message:string)=>{if(process.env.RUMOCA_POSE_TRACE)console.info(message);};
  trace('Preparing complete ES15PoseCorrection session');
  const pose=compiler.WasmSimulationSession.withInteractiveOptions(source,'ES15PoseCorrection',.1,'rk-like',1e-12,1e-12,JSON.stringify(initial));
  trace('Preparing two Modelica SPD6x16 solve sessions');
  const makeSolve=()=>compiler.WasmSimulationSession.withInteractiveOptions(source,'ES15CorrectionSolve',.1,'rk-like',1e-12,1e-12,'[]');
  const noise=makeSolve(),innovationSolve=makeSolve();let frame=0;
  const values=(session:typeof pose)=>JSON.parse(session.state_json()).values as Record<string,number>;
  const readMatrix=(v:Record<string,number>,name:string,n:number,m:number)=>matrix(n,m,(i,j)=>v[`${name}[${i+1},${j+1}]`]);
  function compare(v:Record<string,number>,name:string,expected:number,label:string,tolerance=3e-10){
    expect(Number.isFinite(v[name]),`${label} ${name} finite`).toBe(true);
    expect(Math.abs(v[name]-expected),`${label} ${name}: ${v[name]} != ${expected}`).toBeLessThan(tolerance);
  }
  function checkMatrix(v:Record<string,number>,name:string,a:Matrix,label:string,tol?:number){a.forEach((r,i)=>r.forEach((x,j)=>compare(v,`${name}[${i+1},${j+1}]`,x,label,tol)));}
  function run(s:State,o:Observation,label:string){
    trace(`Evaluating ${label}`);
    frame++;
    pose.set_inputs(JSON.stringify(poseInputs(s,o)));pose.advance_to((2*frame-1)*.1);
    const preview=values(pose),noiseInputs:Input[]=[],solveInputs:Input[]=[];
    putMatrix(noiseInputs,'A',o.C);putMatrix(noiseInputs,'B',zeros(6,16));noise.set_inputs(JSON.stringify(noiseInputs));noise.advance_to(frame*.1);
    putMatrix(solveInputs,'A',readMatrix(preview,'innovation_covariance',6,6));putMatrix(solveInputs,'B',readMatrix(preview,'solve_rhs',6,16));
    innovationSolve.set_inputs(JSON.stringify(solveInputs));innovationSolve.advance_to(frame*.1);
    const solved=values(innovationSolve),finalInputs:Input[]=[['observation_covariance_valid',values(noise).valid],['solve_valid',solved.valid]];
    putMatrix(finalInputs,'solved',readMatrix(solved,'X',6,16));pose.set_inputs(JSON.stringify(finalInputs));pose.advance_to(2*frame*.1);
    const actual=values(pose),expected=reference(s,o);
    expect(actual.accepted,label).toBe(+expected.accepted);
    for(const [name,v] of [['next_accepted_count',expected.next.accepted],['next_rejected_count',expected.next.rejected],['next_last_nis',expected.next.nis]] as const)compare(actual,name,v,label,1e-8);
    checkMatrix(actual,'next_covariance',expected.next.P,label);
    checkMatrix(actual,'next_rotation',rotation(expected.next.q),label);
    for(const [name,v] of [['next_position',expected.next.p],['next_velocity',expected.next.v],['next_accel_bias',expected.next.ba],['next_gyro_bias',expected.next.bg],['next_quaternion',canonicalQ(expected.next.q)]] as const)v.forEach((x,i)=>compare(actual,`${name}[${i+1}]`,x,label));
    if(expected.admissible){
      checkMatrix(actual,'H',expected.H,label);checkMatrix(actual,'cross_covariance',expected.cross,label);
      checkMatrix(actual,'innovation_covariance',expected.S,label);checkMatrix(actual,'solve_rhs',expected.rhs,label);
      checkMatrix(solved,'X',expected.solved,label,1e-8);checkMatrix(actual,'gain',expected.K,label,1e-8);
      expected.innovation.forEach((v,i)=>compare(actual,`innovation[${i+1}]`,v,label,1e-8));
      expected.correction.forEach((v,i)=>compare(actual,`correction[${i+1}]`,v,label,1e-8));
      checkMatrix(actual,'joseph_covariance',expected.joseph,label);
    }
    if(!expected.accepted){
      checkMatrix(actual,'next_covariance',s.P,label,Number.MIN_VALUE);
      checkMatrix(actual,'next_rotation',rotation(s.q),label,Number.MIN_VALUE);
      for(const [name,v] of [['next_position',s.p],['next_velocity',s.v],['next_accel_bias',s.ba],['next_gyro_bias',s.bg]] as const)v.forEach((x,i)=>expect(actual[`${name}[${i+1}]`],label).toBe(x));
    }else{
      const P=readMatrix(actual,'next_covariance',15,15);expect(positiveCovariance(P),label).toBe(true);
      for(let i=0;i<15;i++)for(let j=0;j<15;j++)expect(P[i][j],label).toBe(P[j][i]);
    }
    const readVector=(name:string,n:number)=>Array.from({length:n},(_,i)=>actual[`${name}[${i+1}]`]);
    const actualNext:State={q:readVector('next_quaternion',4) as Quaternion,p:readVector('next_position',3),v:readVector('next_velocity',3),
      ba:readVector('next_accel_bias',3),bg:readVector('next_gyro_bias',3),P:readMatrix(actual,'next_covariance',15,15),
      accepted:actual.next_accepted_count,rejected:actual.next_rejected_count,nis:actual.next_last_nis};
    return {...expected,actualNext};
  }
  try{
    const accepted=run(base(),observation(),'correlated accepted');
    expect(accepted.accepted).toBe(true);expect(accepted.correction.every(v=>Math.abs(v)>1e-8)).toBe(true);
    for(const theta of [[0,0,0],[1e-9,-2e-9,3e-9],[1.01e-7,0,0],[1.1e-7,0,0],[1.3e-6,.5e-6,-.3e-6],[.349,0,0],[.351,0,0],
      [Math.PI-1e-8,0,0],[0,Math.PI-1e-8,0],[0,0,Math.PI-1e-8]])expect(run(base(),observation(theta,[0,0,0]),`angle ${theta}`).accepted).toBe(norm(theta)<=.35);
    for(const axis of [0,1,2])run({...base(),q:expQ(Array.from({length:3},(_,i)=>i===axis?Math.PI-1e-9:0))},observation(),`near-pi nominal quaternion axis${axis}`);
    run({...base(),q:expQ([3.5,.1,-.2])},observation(),'negative quaternion hemisphere');
    const isotropic={...base(),ba:[0,0,0],bg:[0,0,0],P:matrix(15,15,(i,j)=>i===j?.04:0)};
    for(const factor of [1-1e-7,1+1e-7])expect(run(isotropic,{theta:[0,0,0],dp:[Math.sqrt(22.46*.05)*factor,0,0],C:matrix(6,6,(i,j)=>i===j?.01:0)},`NIS ${factor}`).accepted).toBe(factor<1);
    for(const [axis,bias,name] of [[9,1.999,'accel'],[12,.2999,'gyro']] as const){
      const L=matrix(15,15,(i,j)=>i===j?.1:0);L[axis][0]=.8;
      const state={...base(),P:multiply(L,transpose(L)),ba:[0,0,0],bg:[0,0,0]};(axis===9?state.ba:state.bg)[0]=bias;
      expect(run(state,observation([0,0,0],[.02,0,0]),`${name} bias limit`).accepted).toBe(false);
      (axis===9?state.ba:state.bg)[0]=bias/2;
      expect(run(state,observation([0,0,0],[.02,0,0]),`${name} compatible bias`).accepted).toBe(true);
    }
    const badAsym=observation();badAsym.C[0][1]+=.01;
    const badZero=observation();badZero.C=zeros(6,6);
    const badNegative=observation();badNegative.C[5][5]=-1;
    const reflection=observation();reflection.rotation=[[-1,0,0],[0,1,0],[0,0,1]];
    const nonorthogonal=observation();nonorthogonal.rotation=[[1.01,0,0],[0,1,0],[0,0,1]];
    for(const [label,o] of [['asymmetric',badAsym],['zero',badZero],['negative',badNegative],['reflection',reflection],['nonorthogonal',nonorthogonal]] as const)expect(run(base(),o,label).accepted).toBe(false);
    const small=observation();small.C=matrix(6,6,(i,j)=>i===j?1e-14:0);expect(run(base(),small,'strict positive tiny covariance').accepted).toBe(true);
    const rejected=run(accepted.actualNext,observation([.4,0,0],[3,0,0]),'rejected after acceptance');
    expect(rejected.accepted).toBe(false);
    expect(run(rejected.actualNext,observation([.01,-.02,.01],[.005,-.003,.002]),'recovery after rejection').accepted).toBe(true);
  }finally{pose.free();noise.free();innovationSolve.free();}
},60_000);
